danderyd_stations = [

    ["Hägernäs station", "Flygstigen", "Catalinavägen", "Flygsvängen", "Hägernäsvägen", "Björnvägen", "Viggbyskolan", "Norra Bergtorp", 
    "Kemistvägen", "Galoppfältet", "Täby centrum", "Tibbleskolan", "Klubbvägen", "Åva", "Stationsvägen", "Storängsvägen", "Enhagsslingan",
     "Kryddgårdsvägen", "Eneby torg", "Skolvägen", "Fenixvägen", "Enmans väg", "Danderydsberg", "Rinkeby norra", "Mörby centrum", 
     "Danderyds sjukhus"],
    ["Lansen", "Predikantvägen", "Läsargränd", "Myrängsvägen", "Armévägen", "Furuvägen", "Gribbylunds centrum", "Dijkmans väg",
     "Forntidsvägen", "Gribbylunds allé", "Stockholmsvägen", "Gribbylund södra", "Kemistvägen", "Galoppfältet", "Täby centrum", 
     "Grindtorpskyrka", "Grindtorp norra", "Grindtorp södra", "Näsbydal", "Kanalvägen", "Lahällsviadukten", "Mörby centrum",
      "Danderyds sjukhus"],
    ["Täby centrum", "Grindtorpskyrka", "Grindtorp norra", "Grindtorp södra", "Näsbydal", "Kanalvägen", "Lahällsviadukten", 
    "Mörby centrum", "Danderyds sjukhus"],
    ["Edsbergs centrum", "Kruthornsvägen", "Edsbergs sportfält", "Flintlåsvägen", "Yxvägen", "Kvarnskogen", "Rösjön", "Norra Kärrdal",
     "Sjöbergs centrum", "Sjöberg", "Sätra prästgård", "Sätra", "Jaktskyttebanan", "Danarövägen", "Handelsvägen", "Rinkeby västra",
      "Mörby centrum", "Danderyds sjukhus"],
    ["Sollentuna station", "Sofielundsskolan", "Sollentunavallen", "Edsvik", "Edsbacka", "Djupdalsvägen", "Malla Silfverstolpes väg", 
    "Edsbergsskolan", "Edsbergs centrum", "Kruthornsvägen", "Edsbergs sportfält", "Flintlåsvägen", "Yxvägen", "Kvarnskogen", "Rösjön",
     "Norra Kärrdal", "Sjöbergs centrum", "Sjöberg", "Sätra prästgård", "Sätra", "Jaktskyttebanan", "Danarövägen"],
   ["Hägernäs station", "Flygstigen", "Catalinavägen", "Flygsvängen", "Hägernäsvägen", "Björnvägen", "Viggbyskolan", "Norra Bergtorp",
    "Kemistvägen", "Galoppfältet", "Täby centrum", "Tibbleskolan", "Klubbvägen", "Åva", "Stationsvägen", "Storängsvägen", "Enhagsslingan",
     "Kryddgårdsvägen", "Eneby torg", "Skolvägen", "Fenixvägen", "Enmans väg", "Danderydsberg", "Rinkeby norra", "Mörby centrum", 
     "Danderyds sjukhus"],
    ["Lansen", "Predikantvägen", "Läsargränd", "Myrängsvägen", "Armévägen", "Furuvägen", "Gribbylunds centrum", "Dijkmans väg", 
    "Forntidsvägen", "Gribbylunds allé", "Stockholmsvägen", "Gribbylund södra", "Norra Bergtorp", "Viggbyholms trafikplats",
     "Roslags Näsby trafikplats", "Mörby centrum", "Danderyds sjukhus"],
    ["Östra Byle", "Nannavägen", "Bylegård", "Miklagårdsvägen", "Hagmovägen", "Täby kyrka", "Ymervägen", "Karby gård",
     "Täby kyrkby trafikplats", "Parmvägen", "Täbyvägen", "Erikslund", "Anbudsvägen", "Brinkvägen", "Trädgårdsvägen",
      "Milstensvägen", "Ellaparksvägen", "Rösjövägen", "Rostock", "Kryddgårdsvägen", "Eneby torg", "Skolvägen", "Fenixvägen",
       "Enmans väg", "Danderydsberg", "Rinkeby norra", "Mörby centrum", "Danderyds sjukhus"],
    ["Täbyvägen", "Erikslund", "Anbudsvägen", "Brinkvägen", "Trädgårdsvägen", "Milstensvägen", "Ellaparksvägen", "Rösjövägen", 
    "Rostock", "Kryddgårdsvägen", "Eneby torg", "Skolvägen", "Fenixvägen", "Enmans väg", "Danderydsberg", "Rinkeby norra",
     "Mörby centrum", "Danderyds sjukhus"],
    ["Danderyds sjukhus", "Golfvägen", "Rinkeby norra", "Danderydsberg", "Enmans väg", "Fenixvägen", "Skolvägen", 
    "Eneby torg", "Kryddgårdsvägen", "Rostock", "Rosjövägen"]
    ]
